# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/luochen/Documents/Research/projects/stasis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/luochen/Documents/Research/projects/stasis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.13.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/luochen/Documents/Research/projects/stasis/CMakeFiles /Users/luochen/Documents/Research/projects/stasis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/luochen/Documents/Research/projects/stasis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named run_recovery

# Build rule for target.
run_recovery: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_recovery
.PHONY : run_recovery

# fast build rule for target.
run_recovery/fast:
	$(MAKE) -f utilities/CMakeFiles/run_recovery.dir/build.make utilities/CMakeFiles/run_recovery.dir/build
.PHONY : run_recovery/fast

#=============================================================================
# Target rules for targets named truncate_log

# Build rule for target.
truncate_log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 truncate_log
.PHONY : truncate_log

# fast build rule for target.
truncate_log/fast:
	$(MAKE) -f utilities/CMakeFiles/truncate_log.dir/build.make utilities/CMakeFiles/truncate_log.dir/build
.PHONY : truncate_log/fast

#=============================================================================
# Target rules for targets named logfile_dump

# Build rule for target.
logfile_dump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logfile_dump
.PHONY : logfile_dump

# fast build rule for target.
logfile_dump/fast:
	$(MAKE) -f utilities/CMakeFiles/logfile_dump.dir/build.make utilities/CMakeFiles/logfile_dump.dir/build
.PHONY : logfile_dump/fast

#=============================================================================
# Target rules for targets named slotted

# Build rule for target.
slotted: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slotted
.PHONY : slotted

# fast build rule for target.
slotted/fast:
	$(MAKE) -f benchmarks/CMakeFiles/slotted.dir/build.make benchmarks/CMakeFiles/slotted.dir/build
.PHONY : slotted/fast

#=============================================================================
# Target rules for targets named stride

# Build rule for target.
stride: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stride
.PHONY : stride

# fast build rule for target.
stride/fast:
	$(MAKE) -f benchmarks/CMakeFiles/stride.dir/build.make benchmarks/CMakeFiles/stride.dir/build
.PHONY : stride/fast

#=============================================================================
# Target rules for targets named turbine

# Build rule for target.
turbine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 turbine
.PHONY : turbine

# fast build rule for target.
turbine/fast:
	$(MAKE) -f benchmarks/CMakeFiles/turbine.dir/build.make benchmarks/CMakeFiles/turbine.dir/build
.PHONY : turbine/fast

#=============================================================================
# Target rules for targets named redBlackMemoryOverhead

# Build rule for target.
redBlackMemoryOverhead: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 redBlackMemoryOverhead
.PHONY : redBlackMemoryOverhead

# fast build rule for target.
redBlackMemoryOverhead/fast:
	$(MAKE) -f benchmarks/CMakeFiles/redBlackMemoryOverhead.dir/build.make benchmarks/CMakeFiles/redBlackMemoryOverhead.dir/build
.PHONY : redBlackMemoryOverhead/fast

#=============================================================================
# Target rules for targets named naiveHash

# Build rule for target.
naiveHash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 naiveHash
.PHONY : naiveHash

# fast build rule for target.
naiveHash/fast:
	$(MAKE) -f benchmarks/CMakeFiles/naiveHash.dir/build.make benchmarks/CMakeFiles/naiveHash.dir/build
.PHONY : naiveHash/fast

#=============================================================================
# Target rules for targets named distributedLsnFree

# Build rule for target.
distributedLsnFree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distributedLsnFree
.PHONY : distributedLsnFree

# fast build rule for target.
distributedLsnFree/fast:
	$(MAKE) -f benchmarks/CMakeFiles/distributedLsnFree.dir/build.make benchmarks/CMakeFiles/distributedLsnFree.dir/build
.PHONY : distributedLsnFree/fast

#=============================================================================
# Target rules for targets named hashPerformance

# Build rule for target.
hashPerformance: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hashPerformance
.PHONY : hashPerformance

# fast build rule for target.
hashPerformance/fast:
	$(MAKE) -f benchmarks/CMakeFiles/hashPerformance.dir/build.make benchmarks/CMakeFiles/hashPerformance.dir/build
.PHONY : hashPerformance/fast

#=============================================================================
# Target rules for targets named bufferManager

# Build rule for target.
bufferManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bufferManager
.PHONY : bufferManager

# fast build rule for target.
bufferManager/fast:
	$(MAKE) -f benchmarks/CMakeFiles/bufferManager.dir/build.make benchmarks/CMakeFiles/bufferManager.dir/build
.PHONY : bufferManager/fast

#=============================================================================
# Target rules for targets named butterfly

# Build rule for target.
butterfly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 butterfly
.PHONY : butterfly

# fast build rule for target.
butterfly/fast:
	$(MAKE) -f benchmarks/CMakeFiles/butterfly.dir/build.make benchmarks/CMakeFiles/butterfly.dir/build
.PHONY : butterfly/fast

#=============================================================================
# Target rules for targets named seekMap

# Build rule for target.
seekMap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 seekMap
.PHONY : seekMap

# fast build rule for target.
seekMap/fast:
	$(MAKE) -f benchmarks/CMakeFiles/seekMap.dir/build.make benchmarks/CMakeFiles/seekMap.dir/build
.PHONY : seekMap/fast

#=============================================================================
# Target rules for targets named lhtableThreaded

# Build rule for target.
lhtableThreaded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lhtableThreaded
.PHONY : lhtableThreaded

# fast build rule for target.
lhtableThreaded/fast:
	$(MAKE) -f benchmarks/CMakeFiles/lhtableThreaded.dir/build.make benchmarks/CMakeFiles/lhtableThreaded.dir/build
.PHONY : lhtableThreaded/fast

#=============================================================================
# Target rules for targets named linearHashNTAThreaded

# Build rule for target.
linearHashNTAThreaded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linearHashNTAThreaded
.PHONY : linearHashNTAThreaded

# fast build rule for target.
linearHashNTAThreaded/fast:
	$(MAKE) -f benchmarks/CMakeFiles/linearHashNTAThreaded.dir/build.make benchmarks/CMakeFiles/linearHashNTAThreaded.dir/build
.PHONY : linearHashNTAThreaded/fast

#=============================================================================
# Target rules for targets named sequentialThroughput

# Build rule for target.
sequentialThroughput: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sequentialThroughput
.PHONY : sequentialThroughput

# fast build rule for target.
sequentialThroughput/fast:
	$(MAKE) -f benchmarks/CMakeFiles/sequentialThroughput.dir/build.make benchmarks/CMakeFiles/sequentialThroughput.dir/build
.PHONY : sequentialThroughput/fast

#=============================================================================
# Target rules for targets named rawIOPS

# Build rule for target.
rawIOPS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rawIOPS
.PHONY : rawIOPS

# fast build rule for target.
rawIOPS/fast:
	$(MAKE) -f benchmarks/CMakeFiles/rawIOPS.dir/build.make benchmarks/CMakeFiles/rawIOPS.dir/build
.PHONY : rawIOPS/fast

#=============================================================================
# Target rules for targets named linearHashNTAWriteRequests

# Build rule for target.
linearHashNTAWriteRequests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linearHashNTAWriteRequests
.PHONY : linearHashNTAWriteRequests

# fast build rule for target.
linearHashNTAWriteRequests/fast:
	$(MAKE) -f benchmarks/CMakeFiles/linearHashNTAWriteRequests.dir/build.make benchmarks/CMakeFiles/linearHashNTAWriteRequests.dir/build
.PHONY : linearHashNTAWriteRequests/fast

#=============================================================================
# Target rules for targets named roseTable

# Build rule for target.
roseTable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roseTable
.PHONY : roseTable

# fast build rule for target.
roseTable/fast:
	$(MAKE) -f benchmarks/CMakeFiles/roseTable.dir/build.make benchmarks/CMakeFiles/roseTable.dir/build
.PHONY : roseTable/fast

#=============================================================================
# Target rules for targets named arrayListSet

# Build rule for target.
arrayListSet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arrayListSet
.PHONY : arrayListSet

# fast build rule for target.
arrayListSet/fast:
	$(MAKE) -f benchmarks/CMakeFiles/arrayListSet.dir/build.make benchmarks/CMakeFiles/arrayListSet.dir/build
.PHONY : arrayListSet/fast

#=============================================================================
# Target rules for targets named linkedListNTA

# Build rule for target.
linkedListNTA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linkedListNTA
.PHONY : linkedListNTA

# fast build rule for target.
linkedListNTA/fast:
	$(MAKE) -f benchmarks/CMakeFiles/linkedListNTA.dir/build.make benchmarks/CMakeFiles/linkedListNTA.dir/build
.PHONY : linkedListNTA/fast

#=============================================================================
# Target rules for targets named rawSet

# Build rule for target.
rawSet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rawSet
.PHONY : rawSet

# fast build rule for target.
rawSet/fast:
	$(MAKE) -f benchmarks/CMakeFiles/rawSet.dir/build.make benchmarks/CMakeFiles/rawSet.dir/build
.PHONY : rawSet/fast

#=============================================================================
# Target rules for targets named naiveMultiThreaded

# Build rule for target.
naiveMultiThreaded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 naiveMultiThreaded
.PHONY : naiveMultiThreaded

# fast build rule for target.
naiveMultiThreaded/fast:
	$(MAKE) -f benchmarks/CMakeFiles/naiveMultiThreaded.dir/build.make benchmarks/CMakeFiles/naiveMultiThreaded.dir/build
.PHONY : naiveMultiThreaded/fast

#=============================================================================
# Target rules for targets named transitiveClosure

# Build rule for target.
transitiveClosure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 transitiveClosure
.PHONY : transitiveClosure

# fast build rule for target.
transitiveClosure/fast:
	$(MAKE) -f benchmarks/CMakeFiles/transitiveClosure.dir/build.make benchmarks/CMakeFiles/transitiveClosure.dir/build
.PHONY : transitiveClosure/fast

#=============================================================================
# Target rules for targets named linearHashNTA

# Build rule for target.
linearHashNTA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linearHashNTA
.PHONY : linearHashNTA

# fast build rule for target.
linearHashNTA/fast:
	$(MAKE) -f benchmarks/CMakeFiles/linearHashNTA.dir/build.make benchmarks/CMakeFiles/linearHashNTA.dir/build
.PHONY : linearHashNTA/fast

#=============================================================================
# Target rules for targets named qos

# Build rule for target.
qos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qos
.PHONY : qos

# fast build rule for target.
qos/fast:
	$(MAKE) -f benchmarks/CMakeFiles/qos.dir/build.make benchmarks/CMakeFiles/qos.dir/build
.PHONY : qos/fast

#=============================================================================
# Target rules for targets named pageOrientedListNTA

# Build rule for target.
pageOrientedListNTA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pageOrientedListNTA
.PHONY : pageOrientedListNTA

# fast build rule for target.
pageOrientedListNTA/fast:
	$(MAKE) -f benchmarks/CMakeFiles/pageOrientedListNTA.dir/build.make benchmarks/CMakeFiles/pageOrientedListNTA.dir/build
.PHONY : pageOrientedListNTA/fast

#=============================================================================
# Target rules for targets named writeBack

# Build rule for target.
writeBack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 writeBack
.PHONY : writeBack

# fast build rule for target.
writeBack/fast:
	$(MAKE) -f benchmarks/CMakeFiles/writeBack.dir/build.make benchmarks/CMakeFiles/writeBack.dir/build
.PHONY : writeBack/fast

#=============================================================================
# Target rules for targets named roseTableTpcCH-workload2

# Build rule for target.
roseTableTpcCH-workload2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roseTableTpcCH-workload2
.PHONY : roseTableTpcCH-workload2

# fast build rule for target.
roseTableTpcCH-workload2/fast:
	$(MAKE) -f benchmarks/CMakeFiles/roseTableTpcCH-workload2.dir/build.make benchmarks/CMakeFiles/roseTableTpcCH-workload2.dir/build
.PHONY : roseTableTpcCH-workload2/fast

#=============================================================================
# Target rules for targets named rose

# Build rule for target.
rose: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rose
.PHONY : rose

# fast build rule for target.
rose/fast:
	$(MAKE) -f benchmarks/CMakeFiles/rose.dir/build.make benchmarks/CMakeFiles/rose.dir/build
.PHONY : rose/fast

#=============================================================================
# Target rules for targets named linearHashNTAMultiReader

# Build rule for target.
linearHashNTAMultiReader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linearHashNTAMultiReader
.PHONY : linearHashNTAMultiReader

# fast build rule for target.
linearHashNTAMultiReader/fast:
	$(MAKE) -f benchmarks/CMakeFiles/linearHashNTAMultiReader.dir/build.make benchmarks/CMakeFiles/linearHashNTAMultiReader.dir/build
.PHONY : linearHashNTAMultiReader/fast

#=============================================================================
# Target rules for targets named roseTableTpcCH-workload1

# Build rule for target.
roseTableTpcCH-workload1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roseTableTpcCH-workload1
.PHONY : roseTableTpcCH-workload1

# fast build rule for target.
roseTableTpcCH-workload1/fast:
	$(MAKE) -f benchmarks/CMakeFiles/roseTableTpcCH-workload1.dir/build.make benchmarks/CMakeFiles/roseTableTpcCH-workload1.dir/build
.PHONY : roseTableTpcCH-workload1/fast

#=============================================================================
# Target rules for targets named ex3

# Build rule for target.
ex3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ex3
.PHONY : ex3

# fast build rule for target.
ex3/fast:
	$(MAKE) -f examples/CMakeFiles/ex3.dir/build.make examples/CMakeFiles/ex3.dir/build
.PHONY : ex3/fast

#=============================================================================
# Target rules for targets named ex2

# Build rule for target.
ex2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ex2
.PHONY : ex2

# fast build rule for target.
ex2/fast:
	$(MAKE) -f examples/CMakeFiles/ex2.dir/build.make examples/CMakeFiles/ex2.dir/build
.PHONY : ex2/fast

#=============================================================================
# Target rules for targets named ex1

# Build rule for target.
ex1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ex1
.PHONY : ex1

# fast build rule for target.
ex1/fast:
	$(MAKE) -f examples/CMakeFiles/ex1.dir/build.make examples/CMakeFiles/ex1.dir/build
.PHONY : ex1/fast

#=============================================================================
# Target rules for targets named stasis

# Build rule for target.
stasis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stasis
.PHONY : stasis

# fast build rule for target.
stasis/fast:
	$(MAKE) -f src/stasis/CMakeFiles/stasis.dir/build.make src/stasis/CMakeFiles/stasis.dir/build
.PHONY : stasis/fast

#=============================================================================
# Target rules for targets named pobj

# Build rule for target.
pobj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pobj
.PHONY : pobj

# fast build rule for target.
pobj/fast:
	$(MAKE) -f src/pobj/CMakeFiles/pobj.dir/build.make src/pobj/CMakeFiles/pobj.dir/build
.PHONY : pobj/fast

#=============================================================================
# Target rules for targets named buildTable

# Build rule for target.
buildTable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 buildTable
.PHONY : buildTable

# fast build rule for target.
buildTable/fast:
	$(MAKE) -f src/apps/readOnlyHash/CMakeFiles/buildTable.dir/build.make src/apps/readOnlyHash/CMakeFiles/buildTable.dir/build
.PHONY : buildTable/fast

#=============================================================================
# Target rules for targets named queryTable

# Build rule for target.
queryTable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 queryTable
.PHONY : queryTable

# fast build rule for target.
queryTable/fast:
	$(MAKE) -f src/apps/readOnlyHash/CMakeFiles/queryTable.dir/build.make src/apps/readOnlyHash/CMakeFiles/queryTable.dir/build
.PHONY : queryTable/fast

#=============================================================================
# Target rules for targets named check_boundedLog

# Build rule for target.
check_boundedLog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_boundedLog
.PHONY : check_boundedLog

# fast build rule for target.
check_boundedLog/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_boundedLog.dir/build.make test/stasis/CMakeFiles/check_boundedLog.dir/build
.PHONY : check_boundedLog/fast

#=============================================================================
# Target rules for targets named check_rangeTracker

# Build rule for target.
check_rangeTracker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_rangeTracker
.PHONY : check_rangeTracker

# fast build rule for target.
check_rangeTracker/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_rangeTracker.dir/build.make test/stasis/CMakeFiles/check_rangeTracker.dir/build
.PHONY : check_rangeTracker/fast

#=============================================================================
# Target rules for targets named check_io

# Build rule for target.
check_io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_io
.PHONY : check_io

# fast build rule for target.
check_io/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_io.dir/build.make test/stasis/CMakeFiles/check_io.dir/build
.PHONY : check_io/fast

#=============================================================================
# Target rules for targets named check_dirtyPageTable

# Build rule for target.
check_dirtyPageTable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_dirtyPageTable
.PHONY : check_dirtyPageTable

# fast build rule for target.
check_dirtyPageTable/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_dirtyPageTable.dir/build.make test/stasis/CMakeFiles/check_dirtyPageTable.dir/build
.PHONY : check_dirtyPageTable/fast

#=============================================================================
# Target rules for targets named check_bTree

# Build rule for target.
check_bTree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_bTree
.PHONY : check_bTree

# fast build rule for target.
check_bTree/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_bTree.dir/build.make test/stasis/CMakeFiles/check_bTree.dir/build
.PHONY : check_bTree/fast

#=============================================================================
# Target rules for targets named check_pageOrientedList

# Build rule for target.
check_pageOrientedList: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_pageOrientedList
.PHONY : check_pageOrientedList

# fast build rule for target.
check_pageOrientedList/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_pageOrientedList.dir/build.make test/stasis/CMakeFiles/check_pageOrientedList.dir/build
.PHONY : check_pageOrientedList/fast

#=============================================================================
# Target rules for targets named check_linearHashNTA

# Build rule for target.
check_linearHashNTA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_linearHashNTA
.PHONY : check_linearHashNTA

# fast build rule for target.
check_linearHashNTA/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_linearHashNTA.dir/build.make test/stasis/CMakeFiles/check_linearHashNTA.dir/build
.PHONY : check_linearHashNTA/fast

#=============================================================================
# Target rules for targets named check_linkedListNTA

# Build rule for target.
check_linkedListNTA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_linkedListNTA
.PHONY : check_linkedListNTA

# fast build rule for target.
check_linkedListNTA/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_linkedListNTA.dir/build.make test/stasis/CMakeFiles/check_linkedListNTA.dir/build
.PHONY : check_linkedListNTA/fast

#=============================================================================
# Target rules for targets named check_concurrentBTree

# Build rule for target.
check_concurrentBTree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_concurrentBTree
.PHONY : check_concurrentBTree

# fast build rule for target.
check_concurrentBTree/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_concurrentBTree.dir/build.make test/stasis/CMakeFiles/check_concurrentBTree.dir/build
.PHONY : check_concurrentBTree/fast

#=============================================================================
# Target rules for targets named check_min

# Build rule for target.
check_min: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_min
.PHONY : check_min

# fast build rule for target.
check_min/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_min.dir/build.make test/stasis/CMakeFiles/check_min.dir/build
.PHONY : check_min/fast

#=============================================================================
# Target rules for targets named check_header

# Build rule for target.
check_header: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_header
.PHONY : check_header

# fast build rule for target.
check_header/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_header.dir/build.make test/stasis/CMakeFiles/check_header.dir/build
.PHONY : check_header/fast

#=============================================================================
# Target rules for targets named check_hazard

# Build rule for target.
check_hazard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_hazard
.PHONY : check_hazard

# fast build rule for target.
check_hazard/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_hazard.dir/build.make test/stasis/CMakeFiles/check_hazard.dir/build
.PHONY : check_hazard/fast

#=============================================================================
# Target rules for targets named check_linearHash

# Build rule for target.
check_linearHash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_linearHash
.PHONY : check_linearHash

# fast build rule for target.
check_linearHash/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_linearHash.dir/build.make test/stasis/CMakeFiles/check_linearHash.dir/build
.PHONY : check_linearHash/fast

#=============================================================================
# Target rules for targets named check_recovery

# Build rule for target.
check_recovery: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_recovery
.PHONY : check_recovery

# fast build rule for target.
check_recovery/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_recovery.dir/build.make test/stasis/CMakeFiles/check_recovery.dir/build
.PHONY : check_recovery/fast

#=============================================================================
# Target rules for targets named check_regions

# Build rule for target.
check_regions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_regions
.PHONY : check_regions

# fast build rule for target.
check_regions/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_regions.dir/build.make test/stasis/CMakeFiles/check_regions.dir/build
.PHONY : check_regions/fast

#=============================================================================
# Target rules for targets named check_transactional2

# Build rule for target.
check_transactional2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_transactional2
.PHONY : check_transactional2

# fast build rule for target.
check_transactional2/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_transactional2.dir/build.make test/stasis/CMakeFiles/check_transactional2.dir/build
.PHONY : check_transactional2/fast

#=============================================================================
# Target rules for targets named check_operations

# Build rule for target.
check_operations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_operations
.PHONY : check_operations

# fast build rule for target.
check_operations/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_operations.dir/build.make test/stasis/CMakeFiles/check_operations.dir/build
.PHONY : check_operations/fast

#=============================================================================
# Target rules for targets named check_page

# Build rule for target.
check_page: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_page
.PHONY : check_page

# fast build rule for target.
check_page/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_page.dir/build.make test/stasis/CMakeFiles/check_page.dir/build
.PHONY : check_page/fast

#=============================================================================
# Target rules for targets named check_logEntry

# Build rule for target.
check_logEntry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_logEntry
.PHONY : check_logEntry

# fast build rule for target.
check_logEntry/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_logEntry.dir/build.make test/stasis/CMakeFiles/check_logEntry.dir/build
.PHONY : check_logEntry/fast

#=============================================================================
# Target rules for targets named check_redblack

# Build rule for target.
check_redblack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_redblack
.PHONY : check_redblack

# fast build rule for target.
check_redblack/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_redblack.dir/build.make test/stasis/CMakeFiles/check_redblack.dir/build
.PHONY : check_redblack/fast

#=============================================================================
# Target rules for targets named check_concurrentRingbuffer

# Build rule for target.
check_concurrentRingbuffer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_concurrentRingbuffer
.PHONY : check_concurrentRingbuffer

# fast build rule for target.
check_concurrentRingbuffer/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_concurrentRingbuffer.dir/build.make test/stasis/CMakeFiles/check_concurrentRingbuffer.dir/build
.PHONY : check_concurrentRingbuffer/fast

#=============================================================================
# Target rules for targets named check_lhtable

# Build rule for target.
check_lhtable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_lhtable
.PHONY : check_lhtable

# fast build rule for target.
check_lhtable/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_lhtable.dir/build.make test/stasis/CMakeFiles/check_lhtable.dir/build
.PHONY : check_lhtable/fast

#=============================================================================
# Target rules for targets named check_logWriter

# Build rule for target.
check_logWriter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_logWriter
.PHONY : check_logWriter

# fast build rule for target.
check_logWriter/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_logWriter.dir/build.make test/stasis/CMakeFiles/check_logWriter.dir/build
.PHONY : check_logWriter/fast

#=============================================================================
# Target rules for targets named check_concurrentHash

# Build rule for target.
check_concurrentHash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_concurrentHash
.PHONY : check_concurrentHash

# fast build rule for target.
check_concurrentHash/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_concurrentHash.dir/build.make test/stasis/CMakeFiles/check_concurrentHash.dir/build
.PHONY : check_concurrentHash/fast

#=============================================================================
# Target rules for targets named check_blobRecovery

# Build rule for target.
check_blobRecovery: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_blobRecovery
.PHONY : check_blobRecovery

# fast build rule for target.
check_blobRecovery/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_blobRecovery.dir/build.make test/stasis/CMakeFiles/check_blobRecovery.dir/build
.PHONY : check_blobRecovery/fast

#=============================================================================
# Target rules for targets named check_filePool

# Build rule for target.
check_filePool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_filePool
.PHONY : check_filePool

# fast build rule for target.
check_filePool/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_filePool.dir/build.make test/stasis/CMakeFiles/check_filePool.dir/build
.PHONY : check_filePool/fast

#=============================================================================
# Target rules for targets named check_concurrentSkipList

# Build rule for target.
check_concurrentSkipList: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_concurrentSkipList
.PHONY : check_concurrentSkipList

# fast build rule for target.
check_concurrentSkipList/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_concurrentSkipList.dir/build.make test/stasis/CMakeFiles/check_concurrentSkipList.dir/build
.PHONY : check_concurrentSkipList/fast

#=============================================================================
# Target rules for targets named check_bloomFilter

# Build rule for target.
check_bloomFilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_bloomFilter
.PHONY : check_bloomFilter

# fast build rule for target.
check_bloomFilter/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_bloomFilter.dir/build.make test/stasis/CMakeFiles/check_bloomFilter.dir/build
.PHONY : check_bloomFilter/fast

#=============================================================================
# Target rules for targets named check_pageOperations

# Build rule for target.
check_pageOperations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_pageOperations
.PHONY : check_pageOperations

# fast build rule for target.
check_pageOperations/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_pageOperations.dir/build.make test/stasis/CMakeFiles/check_pageOperations.dir/build
.PHONY : check_pageOperations/fast

#=============================================================================
# Target rules for targets named check_replacementPolicy

# Build rule for target.
check_replacementPolicy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_replacementPolicy
.PHONY : check_replacementPolicy

# fast build rule for target.
check_replacementPolicy/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_replacementPolicy.dir/build.make test/stasis/CMakeFiles/check_replacementPolicy.dir/build
.PHONY : check_replacementPolicy/fast

#=============================================================================
# Target rules for targets named check_kiss

# Build rule for target.
check_kiss: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_kiss
.PHONY : check_kiss

# fast build rule for target.
check_kiss/fast:
	$(MAKE) -f test/stasis/CMakeFiles/check_kiss.dir/build.make test/stasis/CMakeFiles/check_kiss.dir/build
.PHONY : check_kiss/fast

#=============================================================================
# Target rules for targets named check_faultInjection

# Build rule for target.
check_faultInjection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_faultInjection
.PHONY : check_faultInjection

# fast build rule for target.
check_faultInjection/fast:
	$(MAKE) -f test/stasis/fault_injection/CMakeFiles/check_faultInjection.dir/build.make test/stasis/fault_injection/CMakeFiles/check_faultInjection.dir/build
.PHONY : check_faultInjection/fast

#=============================================================================
# Target rules for targets named writeLatches

# Build rule for target.
writeLatches: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 writeLatches
.PHONY : writeLatches

# fast build rule for target.
writeLatches/fast:
	$(MAKE) -f benchmarks/multicore/CMakeFiles/writeLatches.dir/build.make benchmarks/multicore/CMakeFiles/writeLatches.dir/build
.PHONY : writeLatches/fast

#=============================================================================
# Target rules for targets named writeLatch

# Build rule for target.
writeLatch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 writeLatch
.PHONY : writeLatch

# fast build rule for target.
writeLatch/fast:
	$(MAKE) -f benchmarks/multicore/CMakeFiles/writeLatch.dir/build.make benchmarks/multicore/CMakeFiles/writeLatch.dir/build
.PHONY : writeLatch/fast

#=============================================================================
# Target rules for targets named readLatches

# Build rule for target.
readLatches: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 readLatches
.PHONY : readLatches

# fast build rule for target.
readLatches/fast:
	$(MAKE) -f benchmarks/multicore/CMakeFiles/readLatches.dir/build.make benchmarks/multicore/CMakeFiles/readLatches.dir/build
.PHONY : readLatches/fast

#=============================================================================
# Target rules for targets named readLatch

# Build rule for target.
readLatch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 readLatch
.PHONY : readLatch

# fast build rule for target.
readLatch/fast:
	$(MAKE) -f benchmarks/multicore/CMakeFiles/readLatch.dir/build.make benchmarks/multicore/CMakeFiles/readLatch.dir/build
.PHONY : readLatch/fast

#=============================================================================
# Target rules for targets named arrayList

# Build rule for target.
arrayList: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arrayList
.PHONY : arrayList

# fast build rule for target.
arrayList/fast:
	$(MAKE) -f benchmarks/multicore/CMakeFiles/arrayList.dir/build.make benchmarks/multicore/CMakeFiles/arrayList.dir/build
.PHONY : arrayList/fast

#=============================================================================
# Target rules for targets named pinSamePage

# Build rule for target.
pinSamePage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pinSamePage
.PHONY : pinSamePage

# fast build rule for target.
pinSamePage/fast:
	$(MAKE) -f benchmarks/multicore/CMakeFiles/pinSamePage.dir/build.make benchmarks/multicore/CMakeFiles/pinSamePage.dir/build
.PHONY : pinSamePage/fast

#=============================================================================
# Target rules for targets named pinDifferentPages

# Build rule for target.
pinDifferentPages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pinDifferentPages
.PHONY : pinDifferentPages

# fast build rule for target.
pinDifferentPages/fast:
	$(MAKE) -f benchmarks/multicore/CMakeFiles/pinDifferentPages.dir/build.make benchmarks/multicore/CMakeFiles/pinDifferentPages.dir/build
.PHONY : pinDifferentPages/fast

#=============================================================================
# Target rules for targets named noopTransactions

# Build rule for target.
noopTransactions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 noopTransactions
.PHONY : noopTransactions

# fast build rule for target.
noopTransactions/fast:
	$(MAKE) -f benchmarks/multicore/CMakeFiles/noopTransactions.dir/build.make benchmarks/multicore/CMakeFiles/noopTransactions.dir/build
.PHONY : noopTransactions/fast

#=============================================================================
# Target rules for targets named hashtableDifferentPages

# Build rule for target.
hashtableDifferentPages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hashtableDifferentPages
.PHONY : hashtableDifferentPages

# fast build rule for target.
hashtableDifferentPages/fast:
	$(MAKE) -f benchmarks/multicore/CMakeFiles/hashtableDifferentPages.dir/build.make benchmarks/multicore/CMakeFiles/hashtableDifferentPages.dir/build
.PHONY : hashtableDifferentPages/fast

#=============================================================================
# Target rules for targets named dirtyPage

# Build rule for target.
dirtyPage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dirtyPage
.PHONY : dirtyPage

# fast build rule for target.
dirtyPage/fast:
	$(MAKE) -f benchmarks/multicore/CMakeFiles/dirtyPage.dir/build.make benchmarks/multicore/CMakeFiles/dirtyPage.dir/build
.PHONY : dirtyPage/fast

#=============================================================================
# Target rules for targets named smallLogEntry

# Build rule for target.
smallLogEntry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smallLogEntry
.PHONY : smallLogEntry

# fast build rule for target.
smallLogEntry/fast:
	$(MAKE) -f benchmarks/multicore/CMakeFiles/smallLogEntry.dir/build.make benchmarks/multicore/CMakeFiles/smallLogEntry.dir/build
.PHONY : smallLogEntry/fast

#=============================================================================
# Target rules for targets named dirtyPages

# Build rule for target.
dirtyPages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dirtyPages
.PHONY : dirtyPages

# fast build rule for target.
dirtyPages/fast:
	$(MAKE) -f benchmarks/multicore/CMakeFiles/dirtyPages.dir/build.make benchmarks/multicore/CMakeFiles/dirtyPages.dir/build
.PHONY : dirtyPages/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousStart"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalUpdate"
	@echo "... install"
	@echo "... ExperimentalStart"
	@echo "... ContinuousSubmit"
	@echo "... ExperimentalTest"
	@echo "... NightlySubmit"
	@echo "... NightlyMemCheck"
	@echo "... test"
	@echo "... ExperimentalConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyTest"
	@echo "... ContinuousMemCheck"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyUpdate"
	@echo "... edit_cache"
	@echo "... NightlyMemoryCheck"
	@echo "... ContinuousConfigure"
	@echo "... Nightly"
	@echo "... NightlyStart"
	@echo "... ExperimentalMemCheck"
	@echo "... Continuous"
	@echo "... Experimental"
	@echo "... run_recovery"
	@echo "... truncate_log"
	@echo "... logfile_dump"
	@echo "... slotted"
	@echo "... stride"
	@echo "... turbine"
	@echo "... redBlackMemoryOverhead"
	@echo "... naiveHash"
	@echo "... distributedLsnFree"
	@echo "... hashPerformance"
	@echo "... bufferManager"
	@echo "... butterfly"
	@echo "... seekMap"
	@echo "... lhtableThreaded"
	@echo "... linearHashNTAThreaded"
	@echo "... sequentialThroughput"
	@echo "... rawIOPS"
	@echo "... linearHashNTAWriteRequests"
	@echo "... roseTable"
	@echo "... arrayListSet"
	@echo "... linkedListNTA"
	@echo "... rawSet"
	@echo "... naiveMultiThreaded"
	@echo "... transitiveClosure"
	@echo "... linearHashNTA"
	@echo "... qos"
	@echo "... pageOrientedListNTA"
	@echo "... writeBack"
	@echo "... roseTableTpcCH-workload2"
	@echo "... rose"
	@echo "... linearHashNTAMultiReader"
	@echo "... roseTableTpcCH-workload1"
	@echo "... ex3"
	@echo "... ex2"
	@echo "... ex1"
	@echo "... stasis"
	@echo "... pobj"
	@echo "... buildTable"
	@echo "... queryTable"
	@echo "... check_boundedLog"
	@echo "... check_rangeTracker"
	@echo "... check_io"
	@echo "... check_dirtyPageTable"
	@echo "... check_bTree"
	@echo "... check_pageOrientedList"
	@echo "... check_linearHashNTA"
	@echo "... check_linkedListNTA"
	@echo "... check_concurrentBTree"
	@echo "... check_min"
	@echo "... check_header"
	@echo "... check_hazard"
	@echo "... check_linearHash"
	@echo "... check_recovery"
	@echo "... check_regions"
	@echo "... check_transactional2"
	@echo "... check_operations"
	@echo "... check_page"
	@echo "... check_logEntry"
	@echo "... check_redblack"
	@echo "... check_concurrentRingbuffer"
	@echo "... check_lhtable"
	@echo "... check_logWriter"
	@echo "... check_concurrentHash"
	@echo "... check_blobRecovery"
	@echo "... check_filePool"
	@echo "... check_concurrentSkipList"
	@echo "... check_bloomFilter"
	@echo "... check_pageOperations"
	@echo "... check_replacementPolicy"
	@echo "... check_kiss"
	@echo "... check_faultInjection"
	@echo "... writeLatches"
	@echo "... writeLatch"
	@echo "... readLatches"
	@echo "... readLatch"
	@echo "... arrayList"
	@echo "... pinSamePage"
	@echo "... pinDifferentPages"
	@echo "... noopTransactions"
	@echo "... hashtableDifferentPages"
	@echo "... dirtyPage"
	@echo "... smallLogEntry"
	@echo "... dirtyPages"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

